### ISSUE TITLE
Exception when starting sidekiq worker

### ISSUE THREAD

**Issue by krichtof** [Association-Merci-Edgar/Merci-Edgar#79]
Sometimes, I've got this exception on the worker after launching `foreman start`

```
20:04:49 worker.1 | 2015-08-18T18:04:49Z 14369 TID-ovh1082es DEBUG: enqueued retry: {"retry":true,"queue":"default","class":"ExportContacts","args":["7c52b0bb79035c4a6b7ab789"],"jid":"7c52b0bb79035c4a6b7ab789","enqueued_at":1439918200.892979,"error_message":"wrong number of arguments (1 for 2)","error_class":"ArgumentError","failed_at":"2015-08-18T17:18:12Z","retry_count":6,"retried_at":"2015-08-18T17:42:37Z"}
20:04:49 worker.1 | 2015-08-18T18:04:49Z 14369 TID-ovh136fa8 ExportContacts JID-7c52b0bb79035c4a6b7ab789 INFO: start
20:04:49 worker.1 | 2015-08-18T18:04:49Z 14369 TID-ovh0ztkrc ExportContacts JID-c634efd5d6ed682e3d82d4bc INFO: start
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 ExportContacts JID-7c52b0bb79035c4a6b7ab789 DEBUG: Failure! Retry 7 in 2520 seconds
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 ExportContacts JID-7c52b0bb79035c4a6b7ab789 INFO: fail: 0.905 sec
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 WARN: {"retry"=>true, "queue"=>"default", "class"=>"ExportContacts", "args"=>["7c52b0bb79035c4a6b7ab789"], "jid"=>"7c52b0bb79035c4a6b7ab789", "enqueued_at"=>1439918200.892979, "error_message"=>"wrong number of arguments (1 for 2)", "error_class"=>"ArgumentError", "failed_at"=>"2015-08-18T17:18:12Z", "retry_count"=>7, "retried_at"=>2015-08-18 18:04:50 UTC}
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 WARN: wrong number of arguments (1 for 2)
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 WARN: /Users/krichtof/src/webapps/edgar2/app/workers/export_contacts.rb:5:in `perform'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:23:in `block in perform'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:21:in `catch'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:21:in `perform'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:48:in `block (3 levels) in process'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:119:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:119:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/rollbar-1.5.1/lib/rollbar/sidekiq.rb:15:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/logging.rb:22:in `with_context'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:124:in `call'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:124:in `invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:47:in `block (2 levels) in process'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:102:in `stats'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:46:in `block in process'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:83:in `do_defer'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:37:in `process'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
20:04:50 worker.1 | /usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
20:04:50 worker.1 | 2015-08-18T18:04:50Z 14369 TID-ovh136fa8 ERROR: Actor crashed!
20:04:50 worker.1 | ArgumentError: wrong number of arguments (1 for 2)
20:04:50 worker.1 | 	/Users/krichtof/src/webapps/edgar2/app/workers/export_contacts.rb:5:in `perform'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:23:in `block in perform'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:21:in `catch'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq_status-1.0.7/lib/sidekiq_status/worker.rb:21:in `perform'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:48:in `block (3 levels) in process'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:119:in `call'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:119:in `block in invoke'
20:04:50 worker.1 | 	/usr/local/rvm/gems/ruby-2.0.0-p645@edgar2/gems/rollbar-1.5.1/lib/rollbar/sidekiq.rb:15:in `call'
```

**Comment by yaf** [comment]
Same here

**Comment by krichtof** [comment]
I just remove all the retry jobs with sidekiq web interface. Surely old jobs before updating perform method signature of the worker. It seems that I don't have the exception anymore.

I wait for one week, and I will close this issue if no exception encountered.
